<a href="https://colab.research.google.com/github/Sourav-Manik/AI-Assignments/blob/main/Assignment_4_Student_Program_Prediction_(Multinomial_Logistic_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.Import Libraries

In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

#2.Import Data

In [ ]:
mdata = pd.read_csv('/content/mdata.csv')
mdata

Unnamed: 0   id  female     ses  schtyp      prog  read  write  math  \
0             1   45  female     low  public  vocation    34     35    41   
1             2  108    male  middle  public   general    34     33    41   
2             3   15    male    high  public  vocation    39     39    44   
3             4   67    male     low  public  vocation    37     37    42   
4             5  153    male  middle  public  vocation    39     31    40   
..          ...  ...     ...     ...     ...       ...   ...    ...   ...   
195         196  100  female    high  public  academic    63     65    71   
196         197  143    male  middle  public  vocation    63     63    75   
197         198   68    male  middle  public  academic    73     67    71   
198         199   57  female  middle  public  academic    71     65    72   
199         200  132    male  middle  public  academic    73     62    73   

     science        honors  
0         29  not enrolled  
1         36  not enrolled  
2         26  not enrolled  
3         33  not enrolled  
4         39  not enrolled  
..       ...           ...  
195       69      enrolled  
196       72      enrolled  
197       63      enrolled  
198       66      enrolled  
199       69      enrolled  

[200 rows x 11 columns]

In [ ]:
# Dependent variable is 'prog' we will use label encoder for this
# Other variable are to be considered as Indeoendent variable and we'll use one hot encoding. 

#3.Data Understanding

In [ ]:
mdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  200 non-null    int64 
 1   id          200 non-null    int64 
 2   female      200 non-null    object
 3   ses         200 non-null    object
 4   schtyp      200 non-null    object
 5   prog        200 non-null    object
 6   read        200 non-null    int64 
 7   write       200 non-null    int64 
 8   math        200 non-null    int64 
 9   science     200 non-null    int64 
 10  honors      200 non-null    object
dtypes: int64(6), object(5)
memory usage: 17.3+ KB


In [ ]:
mdata.isna().sum()

Unnamed: 0    0
id            0
female        0
ses           0
schtyp        0
prog          0
read          0
write         0
math          0
science       0
honors        0
dtype: int64

In [ ]:
mdata

Unnamed: 0   id  female     ses  schtyp      prog  read  write  math  \
0             1   45  female     low  public  vocation    34     35    41   
1             2  108    male  middle  public   general    34     33    41   
2             3   15    male    high  public  vocation    39     39    44   
3             4   67    male     low  public  vocation    37     37    42   
4             5  153    male  middle  public  vocation    39     31    40   
..          ...  ...     ...     ...     ...       ...   ...    ...   ...   
195         196  100  female    high  public  academic    63     65    71   
196         197  143    male  middle  public  vocation    63     63    75   
197         198   68    male  middle  public  academic    73     67    71   
198         199   57  female  middle  public  academic    71     65    72   
199         200  132    male  middle  public  academic    73     62    73   

     science        honors  
0         29  not enrolled  
1         36  not enrolled  
2         26  not enrolled  
3         33  not enrolled  
4         39  not enrolled  
..       ...           ...  
195       69      enrolled  
196       72      enrolled  
197       63      enrolled  
198       66      enrolled  
199       69      enrolled  

[200 rows x 11 columns]

#4.Data Preparation / Preprocessing

In [ ]:
mdata = mdata.drop(['Unnamed: 0','id'],axis = 1)

# del mdata['Unnamed: 0']
# del mdata['id']

In [ ]:
mdata.head()

female     ses  schtyp      prog  read  write  math  science        honors
0  female     low  public  vocation    34     35    41       29  not enrolled
1    male  middle  public   general    34     33    41       36  not enrolled
2    male    high  public  vocation    39     39    44       26  not enrolled
3    male     low  public  vocation    37     37    42       33  not enrolled
4    male  middle  public  vocation    39     31    40       39  not enrolled

In [ ]:
mdata = pd.get_dummies(mdata,columns=['female','ses','schtyp','honors'])

In [ ]:
labelencoder = LabelEncoder()
mdata['prog'] = labelencoder.fit_transform(mdata['prog'])

In [ ]:
mdata.head()

prog  read  write  math  science  female_female  female_male  ses_high  \
0     2    34     35    41       29              1            0         0   
1     1    34     33    41       36              0            1         0   
2     2    39     39    44       26              0            1         1   
3     2    37     37    42       33              0            1         0   
4     2    39     31    40       39              0            1         0   

   ses_low  ses_middle  schtyp_private  schtyp_public  honors_enrolled  \
0        1           0               0              1                0   
1        0           1               0              1                0   
2        0           0               0              1                0   
3        1           0               0              1                0   
4        0           1               0              1                0   

   honors_not enrolled  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1

In [ ]:
mdata.shape

(200, 14)

In [ ]:
mdata.isna().sum()

prog                   0
read                   0
write                  0
math                   0
science                0
female_female          0
female_male            0
ses_high               0
ses_low                0
ses_middle             0
schtyp_private         0
schtyp_public          0
honors_enrolled        0
honors_not enrolled    0
dtype: int64

#5.Model Building

In [ ]:
X = mdata.drop(['prog'],axis = 1)
y = mdata[['prog']]

In [ ]:
X.shape, y.shape

((200, 13), (200, 1))

Standarization

In [ ]:
X_columns = X.columns
X_columns

Index(['read', 'write', 'math', 'science', 'female_female', 'female_male',
       'ses_high', 'ses_low', 'ses_middle', 'schtyp_private', 'schtyp_public',
       'honors_enrolled', 'honors_not enrolled'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
X = std_scaler.fit_transform(X)
X = pd.DataFrame(data = X,columns = X_columns)
X

read     write      math   science  female_female  female_male  \
0   -1.782489 -1.879986 -1.246121 -2.313665       0.913708    -0.913708   
1   -1.782489 -2.091517 -1.246121 -1.604883      -1.094442     1.094442   
2   -1.293600 -1.456923 -0.925094 -2.617428      -1.094442     1.094442   
3   -1.489156 -1.668454 -1.139112 -1.908647      -1.094442     1.094442   
4   -1.293600 -2.303048 -1.353130 -1.301120      -1.094442     1.094442   
..        ...       ...       ...       ...            ...          ...   
195  1.053067  1.292986  1.964153  1.736514       0.913708    -0.913708   
196  1.053067  1.081454  2.392189  2.040278      -1.094442     1.094442   
197  2.030845  1.504517  1.964153  1.128987      -1.094442     1.094442   
198  1.835289  1.292986  2.071162  1.432751       0.913708    -0.913708   
199  2.030845  0.975689  2.178171  1.736514      -1.094442     1.094442   

     ses_high   ses_low  ses_middle  schtyp_private  schtyp_public  \
0   -0.639101  1.804250   -0.951190       -0.436436       0.436436   
1   -0.639101 -0.554247    1.051315       -0.436436       0.436436   
2    1.564697 -0.554247   -0.951190       -0.436436       0.436436   
3   -0.639101  1.804250   -0.951190       -0.436436       0.436436   
4   -0.639101 -0.554247    1.051315       -0.436436       0.436436   
..        ...       ...         ...             ...            ...   
195  1.564697 -0.554247   -0.951190       -0.436436       0.436436   
196 -0.639101 -0.554247    1.051315       -0.436436       0.436436   
197 -0.639101 -0.554247    1.051315       -0.436436       0.436436   
198 -0.639101 -0.554247    1.051315       -0.436436       0.436436   
199 -0.639101 -0.554247    1.051315       -0.436436       0.436436   

     honors_enrolled  honors_not enrolled  
0          -0.600453             0.600453  
1          -0.600453             0.600453  
2          -0.600453             0.600453  
3          -0.600453             0.600453  
4          -0.600453             0.600453  
..               ...                  ...  
195         1.665408            -1.665408  
196         1.665408            -1.665408  
197         1.665408            -1.665408  
198         1.665408            -1.665408  
199         1.665408            -1.665408  

[200 rows x 13 columns]

In [ ]:
X.mean()

read                   2.842171e-16
write                  2.131628e-16
math                  -4.263256e-16
science               -2.131628e-16
female_female         -8.437695e-17
female_male           -8.881784e-17
ses_high               3.552714e-17
ses_low                7.105427e-17
ses_middle             3.108624e-17
schtyp_private        -1.776357e-17
schtyp_public          1.065814e-16
honors_enrolled       -3.552714e-17
honors_not enrolled    3.552714e-17
dtype: float64

In [ ]:
X.std()

read                   1.002509
write                  1.002509
math                   1.002509
science                1.002509
female_female          1.002509
female_male            1.002509
ses_high               1.002509
ses_low                1.002509
ses_middle             1.002509
schtyp_private         1.002509
schtyp_public          1.002509
honors_enrolled        1.002509
honors_not enrolled    1.002509
dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,random_state = 1,shuffle = True,stratify = y)

In [ ]:
X_train.shape , y_train.shape  #training sample

((160, 13), (160, 1))

In [ ]:
X_test.shape , y_test.shape    #test sample

((40, 13), (40, 1))

#6.Model Training

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(multi_class='multinomial', solver='lbfgs')
logistic_model.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(multi_class='multinomial')

In [ ]:
logistic_model.coef_

array([[ 0.25793377,  0.42622127,  0.87941894, -0.49906561, -0.00851565,
         0.00851565,  0.30503025, -0.1400053 , -0.15829613,  0.06426247,
        -0.06426247, -0.06768471,  0.06768471],
       [-0.14191893,  0.15840235, -0.28602027,  0.45640704, -0.08082651,
         0.08082651, -0.05414239,  0.22858617, -0.14488624,  0.03500775,
        -0.03500775, -0.14825581,  0.14825581],
       [-0.11601484, -0.58462362, -0.59339867,  0.04265857,  0.08934216,
        -0.08934216, -0.25088786, -0.08858087,  0.30318236, -0.09927022,
         0.09927022,  0.21594051, -0.21594051]])

In [ ]:
logistic_model.intercept_

array([ 0.58640042, -0.14530628, -0.44109413])

#7.Model Testing

Training Accuracy

In [ ]:
y_train_pred = logistic_model.predict(X_train)

Test Accuracy

In [ ]:
y_test_pred = logistic_model.predict(X_test)

#8.Model Evaluation

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Training Accuracy

In [ ]:
print(accuracy_score(y_train,y_train_pred))

0.69375


In [ ]:
print(confusion_matrix(y_train,y_train_pred))

[[74  4  6]
 [15 11 10]
 [11  3 26]]


In [ ]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.74      0.88      0.80        84
           1       0.61      0.31      0.41        36
           2       0.62      0.65      0.63        40

    accuracy                           0.69       160
   macro avg       0.66      0.61      0.62       160
weighted avg       0.68      0.69      0.67       160



Test Accuracy

In [ ]:
accuracy_score(y_test,y_test_pred)

0.425

#Normalizing the Data and checking the accuracy

In [ ]:
#Normalization of the data
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler


In [ ]:
array = X.values

scaler = MinMaxScaler()
X = scaler.fit_transform(array)

#transformed data
set_printoptions(precision=2)
X

array([[0.12, 0.11, 0.19, ..., 1.  , 0.  , 1.  ],
       [0.12, 0.06, 0.19, ..., 1.  , 0.  , 1.  ],
       [0.23, 0.22, 0.26, ..., 1.  , 0.  , 1.  ],
       ...,
       [0.94, 1.  , 0.9 , ..., 1.  , 1.  , 0.  ],
       [0.9 , 0.94, 0.93, ..., 1.  , 1.  , 0.  ],
       [0.94, 0.86, 0.95, ..., 1.  , 1.  , 0.  ]])

In [ ]:
X = pd.DataFrame(data = X,columns = X_columns)
X

read     write      math   science  female_female  female_male  \
0    0.125000  0.111111  0.190476  0.062500            1.0          0.0   
1    0.125000  0.055556  0.190476  0.208333            0.0          1.0   
2    0.229167  0.222222  0.261905  0.000000            0.0          1.0   
3    0.187500  0.166667  0.214286  0.145833            0.0          1.0   
4    0.229167  0.000000  0.166667  0.270833            0.0          1.0   
..        ...       ...       ...       ...            ...          ...   
195  0.729167  0.944444  0.904762  0.895833            1.0          0.0   
196  0.729167  0.888889  1.000000  0.958333            0.0          1.0   
197  0.937500  1.000000  0.904762  0.770833            0.0          1.0   
198  0.895833  0.944444  0.928571  0.833333            1.0          0.0   
199  0.937500  0.861111  0.952381  0.895833            0.0          1.0   

     ses_high  ses_low  ses_middle  schtyp_private  schtyp_public  \
0         0.0      1.0         0.0             0.0            1.0   
1         0.0      0.0         1.0             0.0            1.0   
2         1.0      0.0         0.0             0.0            1.0   
3         0.0      1.0         0.0             0.0            1.0   
4         0.0      0.0         1.0             0.0            1.0   
..        ...      ...         ...             ...            ...   
195       1.0      0.0         0.0             0.0            1.0   
196       0.0      0.0         1.0             0.0            1.0   
197       0.0      0.0         1.0             0.0            1.0   
198       0.0      0.0         1.0             0.0            1.0   
199       0.0      0.0         1.0             0.0            1.0   

     honors_enrolled  honors_not enrolled  
0                0.0                  1.0  
1                0.0                  1.0  
2                0.0                  1.0  
3                0.0                  1.0  
4                0.0                  1.0  
..               ...                  ...  
195              1.0                  0.0  
196              1.0                  0.0  
197              1.0                  0.0  
198              1.0                  0.0  
199              1.0                  0.0  

[200 rows x 13 columns]

In [ ]:
X.mean()

read                   0.504792
write                  0.604861
math                   0.467738
science                0.538542
female_female          0.545000
female_male            0.455000
ses_high               0.290000
ses_low                0.235000
ses_middle             0.475000
schtyp_private         0.160000
schtyp_public          0.840000
honors_enrolled        0.265000
honors_not enrolled    0.735000
dtype: float64

In [ ]:
X.std()

read                   0.213603
write                  0.263294
math                   0.223058
science                0.206269
female_female          0.499220
female_male            0.499220
ses_high               0.454901
ses_low                0.425063
ses_middle             0.500628
schtyp_private         0.367526
schtyp_public          0.367526
honors_enrolled        0.442441
honors_not enrolled    0.442441
dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,random_state = 1,shuffle = True,stratify = y)

In [ ]:
X_train.shape , y_train.shape  #training sample

((160, 13), (160, 1))

In [ ]:
X_test.shape , y_test.shape    #test sample

((40, 13), (40, 1))

Model Training

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
logistic_model.coef_

array([[ 8.13e-01,  9.52e-01,  1.81e+00, -6.52e-01, -8.25e-04,  1.83e-03,
         5.62e-01, -3.15e-01, -2.46e-01,  2.07e-01, -2.06e-01,  7.07e-02,
        -6.97e-02],
       [-2.30e-01,  3.46e-01, -5.47e-01,  9.96e-01, -1.27e-01,  1.26e-01,
        -1.19e-01,  4.04e-01, -2.86e-01,  8.87e-02, -8.95e-02, -2.70e-01,
         2.69e-01],
       [-5.82e-01, -1.30e+00, -1.27e+00, -3.44e-01,  1.27e-01, -1.28e-01,
        -4.43e-01, -8.94e-02,  5.32e-01, -2.95e-01,  2.95e-01,  1.99e-01,
        -2.00e-01]])

In [ ]:
logistic_model.intercept_

array([-0.72, -0.54,  1.26])

Model Testing

Training Accuracy

In [ ]:
y_train_pred = logistic_model.predict(X_train)

Test Accuracy

In [ ]:
y_test_pred = logistic_model.predict(X_test)

Model Evaluation

Training Accuracy

In [ ]:
print(accuracy_score(y_train,y_train_pred))

0.69375


In [ ]:
print(confusion_matrix(y_train,y_train_pred))

[[75  2  7]
 [16  9 11]
 [12  1 27]]


In [ ]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.73      0.89      0.80        84
           1       0.75      0.25      0.38        36
           2       0.60      0.68      0.64        40

    accuracy                           0.69       160
   macro avg       0.69      0.61      0.60       160
weighted avg       0.70      0.69      0.66       160



Test Accuracy

In [ ]:
accuracy_score(y_test,y_test_pred)

0.45

In [ ]:
mdata.head()

prog  read  write  math  science  female_female  female_male  ses_high  \
0     2    34     35    41       29              1            0         0   
1     1    34     33    41       36              0            1         0   
2     2    39     39    44       26              0            1         1   
3     2    37     37    42       33              0            1         0   
4     2    39     31    40       39              0            1         0   

   ses_low  ses_middle  schtyp_private  schtyp_public  honors_enrolled  \
0        1           0               0              1                0   
1        0           1               0              1                0   
2        0           0               0              1                0   
3        1           0               0              1                0   
4        0           1               0              1                0   

   honors_not enrolled  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1

#Predicting program based on new values

In [ ]:
# define a single row of input data
row = [33,34, 50, 32, 1,0,0,1,0,0,1,0,1]
# predict a multinomial probability distribution
yhat = logistic_model.predict([row])
# summarize the predicted probabilities
print('Predicted value: %s' % yhat[0])

Predicted value: 0


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
