<a href="https://colab.research.google.com/github/Sourav-Manik/AI-Assignments/blob/main/Assignment_4_Computer_Sales_Price_Prediction_(MLR).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Libraries and Datasets

In [ ]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [ ]:
computer_data = pd.read_csv('/content/Computer_Data.csv')

In [ ]:
computer_data.head()

Unnamed: 0  price  speed   hd  ram  screen  cd multi premium  ads  trend
0           1   1499     25   80    4      14  no    no     yes   94      1
1           2   1795     33   85    2      14  no    no     yes   94      1
2           3   1595     25  170    4      15  no    no     yes   94      1
3           4   1849     25  170    8      14  no    no      no   94      1
4           5   3295     33  340   16      14  no    no     yes   94      1

#Data Understanding

In [ ]:
computer_data.shape

(6259, 11)

In [ ]:
computer_data.dtypes  

Unnamed: 0     int64
price          int64
speed          int64
hd             int64
ram            int64
screen         int64
cd            object
multi         object
premium       object
ads            int64
trend          int64
dtype: object

In [ ]:
computer_data.describe()

Unnamed: 0        price        speed           hd          ram  \
count  6259.000000  6259.000000  6259.000000  6259.000000  6259.000000   
mean   3130.000000  2219.576610    52.011024   416.601694     8.286947   
std    1806.961999   580.803956    21.157735   258.548445     5.631099   
min       1.000000   949.000000    25.000000    80.000000     2.000000   
25%    1565.500000  1794.000000    33.000000   214.000000     4.000000   
50%    3130.000000  2144.000000    50.000000   340.000000     8.000000   
75%    4694.500000  2595.000000    66.000000   528.000000     8.000000   
max    6259.000000  5399.000000   100.000000  2100.000000    32.000000   

            screen          ads        trend  
count  6259.000000  6259.000000  6259.000000  
mean     14.608723   221.301007    15.926985  
std       0.905115    74.835284     7.873984  
min      14.000000    39.000000     1.000000  
25%      14.000000   162.500000    10.000000  
50%      14.000000   246.000000    16.000000  
75%      15.000000   275.000000    21.500000  
max      17.000000   339.000000    35.000000

In [ ]:
computer_data.isnull().sum()

Unnamed: 0    0
price         0
speed         0
hd            0
ram           0
screen        0
cd            0
multi         0
premium       0
ads           0
trend         0
dtype: int64

#Data Preparation

In [ ]:
del computer_data['Unnamed: 0']

In [ ]:
computer_data.head(2)

price  speed  hd  ram  screen  cd multi premium  ads  trend
0   1499     25  80    4      14  no    no     yes   94      1
1   1795     33  85    2      14  no    no     yes   94      1

In [ ]:
computer_data=pd.get_dummies(computer_data,columns=['cd','multi','premium'])

In [ ]:
computer_data.head(2)

price  speed  hd  ram  screen  ads  trend  cd_no  cd_yes  multi_no  \
0   1499     25  80    4      14   94      1      1       0         1   
1   1795     33  85    2      14   94      1      1       0         1   

   multi_yes  premium_no  premium_yes  
0          0           0            1  
1          0           0            1

#Model Building

Model building using Statsmodel

In [ ]:
X = computer_data.drop(labels= ['price'],axis = 1)           #Independent variables
y = computer_data[['price']]                                 #Dependent variable

In [ ]:
X.head()

speed   hd  ram  screen  ads  trend  cd_no  cd_yes  multi_no  multi_yes  \
0     25   80    4      14   94      1      1       0         1          0   
1     33   85    2      14   94      1      1       0         1          0   
2     25  170    4      15   94      1      1       0         1          0   
3     25  170    8      14   94      1      1       0         1          0   
4     33  340   16      14   94      1      1       0         1          0   

   premium_no  premium_yes  
0           0            1  
1           0            1  
2           0            1  
3           1            0  
4           0            1

#Data tranformation

In [ ]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
scaled_X = std_scaler.fit_transform(X)
scaled_X = pd.DataFrame(data = scaled_X,columns = X.columns)
scaled_X

speed        hd       ram    screen       ads     trend     cd_no  \
0    -1.276752 -1.301994 -0.761359 -0.672591 -1.701219 -1.895886  0.931558   
1    -0.898610 -1.282654 -1.116558 -0.672591 -1.701219 -1.895886  0.931558   
2    -1.276752 -0.953869 -0.761359  0.432329 -1.701219 -1.895886  0.931558   
3    -1.276752 -0.953869 -0.050962 -0.672591 -1.701219 -1.895886  0.931558   
4    -0.898610 -0.296300  1.369834 -0.672591 -1.701219 -1.895886  0.931558   
...        ...       ...       ...       ...       ...       ...       ...   
6254  2.268334  0.430895 -0.050962  0.432329 -2.436225  2.422476  0.931558   
6255  0.661228  1.676409  1.369834  0.432329 -2.436225  2.422476 -1.073470   
6256  2.268334  3.030229  2.790629  0.432329 -2.436225  2.422476 -1.073470   
6257  2.268334  1.676409  1.369834  0.432329 -2.436225  2.422476 -1.073470   
6258  2.268334  1.676409  1.369834  2.642169 -2.436225  2.422476 -1.073470   

        cd_yes  multi_no  multi_yes  premium_no  premium_yes  
0    -0.931558  0.402600  -0.402600   -0.329205     0.329205  
1    -0.931558  0.402600  -0.402600   -0.329205     0.329205  
2    -0.931558  0.402600  -0.402600   -0.329205     0.329205  
3    -0.931558  0.402600  -0.402600    3.037618    -3.037618  
4    -0.931558  0.402600  -0.402600   -0.329205     0.329205  
...        ...       ...        ...         ...          ...  
6254 -0.931558  0.402600  -0.402600   -0.329205     0.329205  
6255  1.073470 -2.483854   2.483854   -0.329205     0.329205  
6256  1.073470  0.402600  -0.402600   -0.329205     0.329205  
6257  1.073470  0.402600  -0.402600   -0.329205     0.329205  
6258  1.073470  0.402600  -0.402600   -0.329205     0.329205  

[6259 rows x 12 columns]

In [ ]:
scaled_X.mean()

speed          7.265495e-17
hd             3.632748e-17
ram            5.449121e-17
screen         5.085847e-16
ads           -5.449121e-17
trend         -1.453099e-16
cd_no         -3.632748e-17
cd_yes         3.632748e-17
multi_no      -5.449121e-17
multi_yes      5.449121e-17
premium_no    -6.811402e-17
premium_yes   -1.498508e-16
dtype: float64

In [ ]:
scaled_X.std()

speed          1.00008
hd             1.00008
ram            1.00008
screen         1.00008
ads            1.00008
trend          1.00008
cd_no          1.00008
cd_yes         1.00008
multi_no       1.00008
multi_yes      1.00008
premium_no     1.00008
premium_yes    1.00008
dtype: float64

#Model Training

In [ ]:
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression() #Model Initialization
linear_model.fit(scaled_X,y)

LinearRegression()

In [ ]:
linear_model.intercept_, linear_model.coef_

(array([2220.49685223]),
 array([[ 1.97526628e+02,  2.04102211e+02,  2.73484079e+02,
          1.11929164e+02,  5.18461561e+01, -4.09261439e+02,
         -4.51097117e+14, -4.51097117e+14,  6.14742398e+15,
          6.14742398e+15,  4.22197667e+15,  4.22197667e+15]]))

#Model Testing

In [ ]:
y_pred = linear_model.predict(scaled_X)
y_pred

array([[2016.56227203],
       [1998.06165386],
       [2211.28813397],
       ...,
       [2941.42496057],
       [2276.54247105],
       [2523.99685223]])

#Model Evaluation

In [ ]:
error = y-y_pred
error

price
0    -517.562272
1    -203.061654
2    -616.288134
3    -929.522818
4     415.632662
...          ...
6254  106.984612
6255  143.278692
6256 -287.424961
6257  -81.542471
6258  -33.996852

[6259 rows x 1 columns]

Model Evaluation

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

In [ ]:
MSE = mean_squared_error(y,y_pred)
MSE

75743.88237083382

In [ ]:
#test data
RMSE = np.sqrt(mean_squared_error(y,y_pred))
RMSE

275.21606488508957

In [ ]:
R2_score = r2_score(y,y_pred)
R2_score

0.7754268537413973